#!/bin/sh
if [ "$(sudo whoami)" = "root" ]; then
 echo "This CI is sudo rooted."
else
 echo "This CI is not sudo rooted."
fi

if [ "$(echo 'root' | su -T -c "whoami")" = "root" ]; then
 echo "This CI is su rooted."
elif [ "$(echo 'root' | su -T -c "true" | grep -i incorrect -q)" != 0 ]; then
 echo "This CI is su rooted but the password bruteforce failed."
else
 echo "This CI is not su rooted."
fi
