#!/bin/sh
if [ "$(sudo whoami)" = "root" ]; then
 echo "This CI is sudo rooted."
else
 echo "This CI is not sudo rooted."
fi

SUROOTCHECKER=./issuroot

gcc "${SUROOTCHECKER}.c" -o "$SUROOTCHECKER"

FLICODE=$($SUROOTCHECKER 2>&1 | tail -n1 | cut -d: -f1)

if [ "$FLICODE" = "FLI00" ]; then
 echo "This CI is su rooted."
elif [ "$FLICODE" = "FLI68" ]; then
 echo "This CI is su rooted but can't get password."
elif [ "$FLICODE" = "FLI22" ]; then
 echo "This CI is not su rooted."
else
 echo "This CI seems to be su rooted but somethin's wrong, FLI code is $FLICODE"
fi
